steps:
- powershell: >
    Write-Host (
    '##vso[task.setvariable variable=LayoutCmd]&
    "{0}\bin\python.exe"
    "{1}\PC\layout"
    -vv
    --source "{1}"
    --build "{0}\bin"
    --temp "{0}\layout-temp"
    --include-cat "{0}\bin\python.cat"
    --doc-build "{0}\doc"'
    -f ("$(Build.BinariesDirectory)", "$(Build.SourcesDirectory)")
    )
  displayName: 'Set LayoutCmd'
